name: Deploy to Google Cloud VM

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

      - name: Deploy to Google Cloud VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USER }}@${{ secrets.GCP_VM_IP }} << EOF
            docker-compose -f ./docker-compose.yml down
            docker-compose -f ./docker-compose.yml pull
            docker-compose -f ./docker-compose.yml up -d
          EOF
